services:
  wireguard-sip-proxy:
    image: ghcr.io/leicraftmc/wireguard-sip-proxy
    container_name: wireguard-sip-proxy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "5060:5060/udp"
      - "10000-10100:10000-10100/udp"
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./config/asterisk:/etc/asterisk
      - ./config/wireguard:/etc/wireguard